services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assistant_pedago_dev
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/myvenv
      - hf_cache:/root/.cache/huggingface    # ← monté ici
    # --- AJOUTE CETTE LIGNE ICI ---
    env_file:
      - .env
    # ------------------------------
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: python Flask_WEBI/app.py

volumes:
  hf_cache:    # ← ET ÇA EN BAS